# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('studentid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('github', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('-studentid',),
            },
        ),
    ]
