# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170814_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(),
        ),
    ]
