# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homework_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='check_result',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='self_check_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='self_check_result',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='allow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='check_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='ontime_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homework',
            name='download',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='repo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pass_percent',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='upload_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
