# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170816_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
