# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170816_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-student_id',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-student_id',)},
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='download',
            new_name='download_limit',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='issueid',
            new_name='issue_id',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='studentid',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='allow',
            new_name='allow_submit',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='url',
            new_name='requset_url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='studentid',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='self_check_description',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='self_check_result',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='ontime_percent',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='pass_percent',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='upload_percent',
        ),
        migrations.AddField(
            model_name='homework',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
