# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170817_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='requset_url',
            new_name='request_url',
        ),
    ]
