# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170817_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
