# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170817_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='check_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='download_limit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='repo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
