# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_issue_issued_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
