# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170822_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-issue_id',)},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='student_id',
        ),
    ]
