# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170822_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('-student_id',)},
        ),
        migrations.AddField(
            model_name='homework',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
