# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20170823_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='request_url',
        ),
        migrations.AddField(
            model_name='issue',
            name='closeline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
