# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_panding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panding',
            new_name='Pending',
        ),
    ]
