# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170825_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='repo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
